#!/bin/bash
# generate_autorun_header.sh - Reads autorun.conf and generates C header with embedded data
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUTORUN_DIR="${SCRIPT_DIR}/autorun"
OUTPUT_DIR="${SCRIPT_DIR}/autorun_embedded"
CONFIG_FILE="${AUTORUN_DIR}/autorun.conf"
H_FILE="${OUTPUT_DIR}/autorun_release.h"

mkdir -p "${OUTPUT_DIR}"

if [ ! -f "${CONFIG_FILE}" ]; then
    echo "No autorun.conf found, generating empty header"
    cat > "${H_FILE}" << 'EOF'
#ifndef AUTORUN_RELEASE_H
#define AUTORUN_RELEASE_H
static inline void release_autorun_files(void) {}
#endif
EOF
    exit 0
fi

ENTRIES=()
while IFS=' ' read -r src_file target_path mode || [ -n "${src_file}" ]; do
    [[ "${src_file}" == \#* ]] && continue
    [ -z "${src_file}" ] && continue
    src_path="${AUTORUN_DIR}/${src_file}"
    if [ ! -f "${src_path}" ]; then
        echo "Warning: ${src_path} not found, skipping"
        continue
    fi
    ENTRIES+=("${src_file}|${target_path}|${mode}")
done < "${CONFIG_FILE}"

if [ ${#ENTRIES[@]} -eq 0 ]; then
    echo "No valid entries, generating empty header"
    cat > "${H_FILE}" << 'EOF'
#ifndef AUTORUN_RELEASE_H
#define AUTORUN_RELEASE_H
static inline void release_autorun_files(void) {}
#endif
EOF
    exit 0
fi

echo "Generating autorun_release.h with ${#ENTRIES[@]} entry/entries..."

cat > "${H_FILE}" << 'HEADER_TOP'
#ifndef AUTORUN_RELEASE_H
#define AUTORUN_RELEASE_H
// Auto-generated by generate_autorun_header.sh - DO NOT EDIT

HEADER_TOP

for entry in "${ENTRIES[@]}"; do
    IFS='|' read -r src_file target_path mode <<< "${entry}"
    src_path="${AUTORUN_DIR}/${src_file}"
    var_name=$(echo "${src_file}" | sed 's/[^a-zA-Z0-9]/_/g')
    file_size=$(wc -c < "${src_path}")

    echo "// ${src_file} -> ${target_path} (${file_size} bytes, mode ${mode})" >> "${H_FILE}"
    echo "static const unsigned char ${var_name}_data[] = {" >> "${H_FILE}"
    # Convert binary to C hex array using od + awk
    # Each hex byte gets " 0xXX," format; trailing comma before } is valid C
    od -A n -t x1 "${src_path}" | awk '
    {
        gsub(/^[[:space:]]+/, "");
        gsub(/[[:space:]]+$/, "");
        split($0, parts, " ");
        for (i = 1; i <= length(parts); i++) {
            if (parts[i] != "") {
                printf " 0x%s,", parts[i]
            }
        }
        printf "\n"
    }' >> "${H_FILE}"
    echo "};" >> "${H_FILE}"
    echo "static const size_t ${var_name}_size = sizeof(${var_name}_data);" >> "${H_FILE}"
    echo "static const char ${var_name}_target[] = \"${target_path}\";" >> "${H_FILE}"
    echo "static const unsigned int ${var_name}_mode = ${mode};" >> "${H_FILE}"
    echo "" >> "${H_FILE}"
done

cat >> "${H_FILE}" << 'FUNC_TOP'
static inline void release_autorun_files(void)
{
    struct file *fp;
    loff_t pos;
    int ret;

FUNC_TOP

for entry in "${ENTRIES[@]}"; do
    IFS='|' read -r src_file target_path mode <<< "${entry}"
    var_name=$(echo "${src_file}" | sed 's/[^a-zA-Z0-9]/_/g')
    cat >> "${H_FILE}" << EOF
    // Release ${src_file}
    if (${var_name}_size > 0) {
        struct path ${var_name}_p;
        if (kern_path(${var_name}_target, LOOKUP_FOLLOW, &${var_name}_p) == 0) {
            path_put(&${var_name}_p);
            pr_info("KernelSU: %s exists, skipping\\n", ${var_name}_target);
        } else {
            fp = filp_open(${var_name}_target, O_WRONLY | O_CREAT | O_TRUNC, ${var_name}_mode);
            if (IS_ERR(fp)) {
                pr_err("KernelSU: failed to open %s, err: %ld\\n", ${var_name}_target, PTR_ERR(fp));
            } else {
                pos = 0;
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 14, 0)
                ret = kernel_write(fp, ${var_name}_data, ${var_name}_size, &pos);
#else
                ret = kernel_write(fp, ${var_name}_data, ${var_name}_size, pos);
#endif
                filp_close(fp, NULL);
                if (ret == ${var_name}_size) {
                    pr_info("KernelSU: released %s (%u bytes)\\n", ${var_name}_target, ${var_name}_size);
                } else {
                    pr_err("KernelSU: failed to write %s\\n", ${var_name}_target);
                }
            }
        }
    }
EOF
done

echo "}" >> "${H_FILE}"
echo "" >> "${H_FILE}"
echo "#endif /* AUTORUN_RELEASE_H */" >> "${H_FILE}"

echo "Generated ${H_FILE} (${#ENTRIES[@]} entries)"
ls -la "${H_FILE}"
